package org.ironriders.manipulation.launcher;

import static edu.wpi.first.units.Units.Degrees;

import java.util.List;

import org.ironriders.lib.InterpolatingDoubleMap;

import edu.wpi.first.units.measure.Angle;

public class LauncherMaps {
    public AngleToExtensionMap angleToExtensionMap;
    public LauncherAngleToDistanceMap launcherAngleToDistanceMap;

    /*
     * Setup maps.
     */
    public LauncherMaps() {
        this.angleToExtensionMap = new AngleToExtensionMap();
        this.launcherAngleToDistanceMap = new LauncherAngleToDistanceMap();
    }

    public class LauncherAngleToDistanceMap {
        public static InterpolatingDoubleMap launcherAngleToDistanceMap = new InterpolatingDoubleMap();

        LauncherAngleToDistanceMap() {
            launcherAngleToDistanceMap.put(90d, 0d);
            launcherAngleToDistanceMap.put(35d, 10d);
            launcherAngleToDistanceMap.put(45d, 15d);
        }

        public static Angle getAngleToHubForDistance(double distance) {
            return Angle.ofBaseUnits(launcherAngleToDistanceMap.get(distance), Degrees);
        }
    }

    public class AngleToExtensionMap {
        public static InterpolatingDoubleMap angleToExtensionMap = new InterpolatingDoubleMap();

        // See: https://tinyurl.com/3smfzd2v and
        // https://wcproducts.com/products/wcp-0415 for info.
        public static double strokeLength = 140; // mm
        public static double maxExtension = strokeLength * 2;

        AngleToExtensionMap() {
            /*
             * Key: Angle, Value: Extension Amount (mm)
             * Values currently from CAD, generated by script at
             * https://fs.suwiesi.dev/public/angles.py
             * 
             * Run with:
             * curl https://fs.suwiesi.dev/public/angles.py | python -
             */
            angleToExtensionMap.put(0d, 0d);
            angleToExtensionMap.put(1d, 3.67d);
            angleToExtensionMap.put(2d, 7.34d);
            angleToExtensionMap.put(3d, 11.0d);
            angleToExtensionMap.put(4d, 14.66d);
            angleToExtensionMap.put(5d, 18.31d);
            angleToExtensionMap.put(6d, 21.95d);
            angleToExtensionMap.put(7d, 25.57d);
            angleToExtensionMap.put(8d, 29.18d);
            angleToExtensionMap.put(9d, 32.77d);
            angleToExtensionMap.put(10d, 36.35d);
            angleToExtensionMap.put(11d, 39.9d);
            angleToExtensionMap.put(12d, 43.43d);
            angleToExtensionMap.put(13d, 46.93d);
            angleToExtensionMap.put(14d, 50.41d);
            angleToExtensionMap.put(15d, 53.86d);
            angleToExtensionMap.put(16d, 57.28d);
            angleToExtensionMap.put(17d, 60.67d);
            angleToExtensionMap.put(18d, 64.03d);
            angleToExtensionMap.put(19d, 67.35d);
            angleToExtensionMap.put(20d, 70.64d);
            angleToExtensionMap.put(21d, 73.9d);
            angleToExtensionMap.put(22d, 77.11d);
            angleToExtensionMap.put(23d, 80.3d);
            angleToExtensionMap.put(24d, 83.44d);
            angleToExtensionMap.put(25d, 86.54d);
            angleToExtensionMap.put(26d, 89.61d);
            angleToExtensionMap.put(27d, 92.63d);
            angleToExtensionMap.put(28d, 95.61d);
            angleToExtensionMap.put(29d, 98.56d);
            angleToExtensionMap.put(30d, 101.46d);
            angleToExtensionMap.put(31d, 104.32d);
            angleToExtensionMap.put(32d, 107.14d);
            angleToExtensionMap.put(33d, 109.92d);
            angleToExtensionMap.put(34d, 112.65d);
            angleToExtensionMap.put(35d, 115.35d);
            angleToExtensionMap.put(36d, 118.0d);
            angleToExtensionMap.put(37d, 120.61d);
            angleToExtensionMap.put(38d, 123.18d);
            angleToExtensionMap.put(39d, 125.71d);
            angleToExtensionMap.put(40d, 128.2d);
            angleToExtensionMap.put(41d, 130.65d);
            angleToExtensionMap.put(42d, 133.05d);
            angleToExtensionMap.put(43d, 135.42d);
            angleToExtensionMap.put(44d, 137.75d);
            angleToExtensionMap.put(45d, 140.04d);
            angleToExtensionMap.put(46d, 142.29d);
            angleToExtensionMap.put(47d, 144.51d);
            angleToExtensionMap.put(48d, 146.68d);
            angleToExtensionMap.put(49d, 148.82d);
            angleToExtensionMap.put(50d, 150.92d);
            angleToExtensionMap.put(51d, 152.99d);
            angleToExtensionMap.put(52d, 155.02d);
            angleToExtensionMap.put(53d, 157.02d);
            angleToExtensionMap.put(54d, 158.98d);
            angleToExtensionMap.put(55d, 160.9d);
            angleToExtensionMap.put(56d, 162.8d);
            angleToExtensionMap.put(57d, 164.66d);
            angleToExtensionMap.put(58d, 166.49d);
            angleToExtensionMap.put(59d, 168.29d);
            angleToExtensionMap.put(60d, 170.05d);
            angleToExtensionMap.put(61d, 171.79d);
            angleToExtensionMap.put(62d, 173.49d);
            angleToExtensionMap.put(63d, 175.17d);
            angleToExtensionMap.put(64d, 176.82d);
            angleToExtensionMap.put(65d, 178.44d);
            angleToExtensionMap.put(66d, 180.03d);
            angleToExtensionMap.put(67d, 181.59d);
            angleToExtensionMap.put(68d, 183.13d);
            angleToExtensionMap.put(69d, 184.64d);
            angleToExtensionMap.put(70d, 186.13d);
            angleToExtensionMap.put(71d, 187.59d);
            angleToExtensionMap.put(72d, 189.02d);
            angleToExtensionMap.put(73d, 190.43d);
            angleToExtensionMap.put(74d, 191.82d);
            angleToExtensionMap.put(75d, 193.19d);
            angleToExtensionMap.put(76d, 194.53d);
            angleToExtensionMap.put(77d, 195.85d);
            angleToExtensionMap.put(78d, 197.14d);
            angleToExtensionMap.put(79d, 198.42d);
            angleToExtensionMap.put(80d, 199.68d);
            angleToExtensionMap.put(81d, 200.91d);
            angleToExtensionMap.put(82d, 202.12d);
            angleToExtensionMap.put(83d, 203.32d);
            angleToExtensionMap.put(84d, 204.49d);
            angleToExtensionMap.put(85d, 205.65d);
            angleToExtensionMap.put(86d, 206.79d);
            angleToExtensionMap.put(87d, 207.91d);
            angleToExtensionMap.put(88d, 209.01d);
            angleToExtensionMap.put(89d, 210.09d);
            angleToExtensionMap.put(90d, 211.16d);
            angleToExtensionMap.put(91d, 212.21d);
            angleToExtensionMap.put(92d, 213.25d);
            angleToExtensionMap.put(93d, 214.26d);
            angleToExtensionMap.put(94d, 215.27d);
            angleToExtensionMap.put(95d, 216.25d);
            angleToExtensionMap.put(96d, 217.22d);
            angleToExtensionMap.put(97d, 218.18d);
            angleToExtensionMap.put(98d, 219.12d);
            angleToExtensionMap.put(99d, 220.05d);
            angleToExtensionMap.put(100d, 220.97d);
            angleToExtensionMap.put(101d, 221.87d);
            angleToExtensionMap.put(102d, 222.75d);
            angleToExtensionMap.put(103d, 223.63d);
            angleToExtensionMap.put(104d, 224.49d);
            angleToExtensionMap.put(105d, 225.34d);
            angleToExtensionMap.put(106d, 226.17d);
            angleToExtensionMap.put(107d, 227.0d);
            angleToExtensionMap.put(108d, 227.81d);
            angleToExtensionMap.put(109d, 228.61d);
            angleToExtensionMap.put(110d, 229.4d);
            angleToExtensionMap.put(111d, 230.18d);
            angleToExtensionMap.put(112d, 230.94d);
            angleToExtensionMap.put(113d, 231.7d);
            angleToExtensionMap.put(114d, 232.45d);
            angleToExtensionMap.put(115d, 233.18d);
            angleToExtensionMap.put(116d, 233.91d);
            angleToExtensionMap.put(117d, 234.62d);
            angleToExtensionMap.put(118d, 235.33d);
            angleToExtensionMap.put(119d, 236.02d);
            angleToExtensionMap.put(120d, 236.71d);
            angleToExtensionMap.put(121d, 237.39d);
            angleToExtensionMap.put(122d, 238.05d);
            angleToExtensionMap.put(123d, 238.71d);
            angleToExtensionMap.put(124d, 239.36d);
            angleToExtensionMap.put(125d, 240.0d);
        }

        /*
         * Get the value in terms of 0-1 instead of raw millimeters.
         * You should probably use this method in most cases.
         */
        public static double getExtensionForAngle(double angle) {
            return angleToExtensionMap.get(angle) / maxExtension;
        }

        /*
         * Get the angle for the given extension (0-1).
         */
        public static double getAngleForExtensionPercent(double extension) {
            return angleToExtensionMap.getKeysByValue(extension * maxExtension).orElse(List.of(0d)).get(0);
        }

        /*
         * Get the angle for the given extension in mm.
         */
        public static double getAngleForExtension(double extension) {
            return angleToExtensionMap.getKeysByValue(extension).orElse(List.of(0d)).get(0);
        }
    }
}
